apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
  namespace: gitops
spec:
  replicas: 8
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: nginx:1.27.5
        ports:
        - containerPort: 80
